### ISSUE TITLE
jssrc2cpg: Invalid IMPORTS Edge on IMPORT Node

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#2168] opened 2023-01-07 11:10 UTC
Given the test code:

```scala
  "foo" in {
    val cpg: Cpg = code(
      """
        |const mongoose = require('mongoose');
        |mongoose.model('abc', { title: { type: String }});
        |""".stripMargin)
  }
  ```
  I get the exception `Edge with type='IMPORTS' with direction='OUT' not supported by nodeType='IMPORT'`. Changing the `require('mongoose')` to `null` results in a passing CPG creation.
  
  Joern version: 1.1.1378

**Comment by max-leuthaeuser** [comment] 2023-01-08 08:58
Looks like this came in with https://github.com/joernio/joern/pull/1861

**Comment by fabsx00** [comment] 2023-01-08 09:02
I can't reproduce this on joern master, looks like a setup issue.

**Comment by fabsx00** [comment] 2023-01-08 09:03
Closing for now.

**Closed by fabsx00** 2023-01-08 09:03 UTC

**Comment by DavidBakerEffendi** [comment] 2023-01-09 06:48
Confirmed this is a setup issue, with older versions of CPG/OverflowDB running behind a newer Joern
