### ISSUE TITLE
[Bug][rubysrc2cpg] - 1:4 no viable alternative at input ' %w'  

### ISSUE THREAD

**Issue by pandurangpatil** [joernio/joern#3167] opened 2023-07-20 15:12 UTC
**Describe the bug**
Getting parser error "1:4 no viable alternative at input ' %w'"

**To Reproduce**
code to reproduce the error

```
    %w[stripe braintree paddle fake_processor].each do |processor_name|
      puts processor_name
    end
```

**Comment by pandurangpatil** [comment] 2023-07-20 15:12
@xavierpinho tagging you for parser errors

**Comment by xavierpinho** [comment] 2023-07-21 10:38
Thanks for the sample, but closing this as a duplicate of #3040

**Closed by xavierpinho** 2023-07-21 10:38 UTC
Labels: bug
