### ISSUE TITLE
[Bug] [RubySrc2Cpg] - IdentifierToCallPass is breaking

### ISSUE THREAD

**Issue by khemrajrathore** [joernio/joern#4016] opened 2024-01-01 14:18 UTC
**Describe the bug**
The pass `IdentifierToCallPass` introduced in the [PR](https://github.com/joernio/joern/pull/3611), is breaking on the repo - https://github.com/pay-rails/pay.git

**To Reproduce**
1.Scan the repo using the deprecated Ruby frontend

**Expected behavior**
The repo should get scanned and the pass `IdentifierToCallPass` should also pass successfully

Looks like when we are doing an instant replacement, we assume that the to-be-deleted (identifier) nodes will never be encountered when we traverse further referencing Identifier nodes. This is not true, and overlapping may occur for identifier nodes connected via  `CFG`/`PostDominate` related Edges

**Comment by fabsx00** [comment] 2024-01-03 17:11
I was able to reproduce the issue on master by invoking `importCode.rubyDeprecated("/path/to/code")`.

**Comment by fabsx00** [comment] 2024-01-03 17:18
The stack trace seems to indicate that we are referring to a node that cannot be found, and this seems to be a result of `convertToCall` as commenting out the body of that method makes the import succeed.

**Comment by fabsx00** [comment] 2024-01-03 17:30
When removing all `removeNode/removeEdge` operations in `convertToCall`, the import succeeds, so, my guess is that we are asking for something to be removed that does not exist.

**Comment by fabsx00** [comment] 2024-01-03 17:51
It seems that we are attempting to remove the same nodes/edges multiple times. I was able to confirm that at least for the `LOCAL` nodes, for which I now have a patch.

**Comment by DavidBakerEffendi** [comment] 2024-01-08 08:24
Resolved by https://github.com/joernio/joern/pull/4021

**Closed by DavidBakerEffendi** 2024-01-08 08:24 UTC
Labels: bug
