### ISSUE TITLE
[Bug][rubysec2cpg] - dynamically interpolated string

### ISSUE THREAD

**Issue by ankit-privado** [joernio/joern#3208] opened 2023-07-23 19:48 UTC
Describe the bug
getting parser error -  `no viable alternative at input ':"'`

To Reproduce

parse the below code: 
```
v = :"name_#{value}_path"
```

**Comment by xavierpinho** [comment] 2023-07-24 09:45
Thanks for the sample, but closing this as a duplicate of #3205

**Closed by xavierpinho** 2023-07-24 09:45 UTC
Labels: bug
