### ISSUE TITLE
Joern fails:  Unable to create a system terminal, creating a dumb terminal

### ISSUE THREAD

**Issue by lyriccoder** [joernio/joern#4284] opened 2024-03-06 13:19 UTC
If I install Joern using ./joern-install.sh and then attempt to run it in a Docker container, it fails with an error.

```
#49 5.027 WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
#49 5.084 Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal
#49 5.084       at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:323)
#49 5.084       at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:265)
#49 5.084       at replpp.JLineTerminal.<init>(JLineTerminal.scala:28)
#49 5.084       at replpp.ReplDriver$$anon$1.<init>(ReplDriver.scala:26)
#49 5.084       at replpp.ReplDriver.runUntilQuit(ReplDriver.scala:28)
#49 5.084       at replpp.InteractiveShell$.run(InteractiveShell.scala:36)
#49 5.084       at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:243)
#49 5.084       at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:230)
#49 5.084       at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:6)
#49 5.084       at io.joern.console.BridgeBase.run(BridgeBase.scala:210)
#49 5.084       at io.joern.console.BridgeBase.run$(BridgeBase.scala:43)
#49 5.084       at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:6)
#49 5.084       at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:11)
#49 5.084       at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala)
#49 ERROR: process "/bin/sh -c joern" did not complete successfully: exit code: 1
------
 > [45/45] RUN joern:
#49 5.084       at replpp.ReplDriver.runUntilQuit(ReplDriver.scala:28)
#49 5.084       at replpp.InteractiveShell$.run(InteractiveShell.scala:36)
#49 5.084       at io.joern.console.InteractiveShell.startInteractiveShell(BridgeBase.scala:243)
#49 5.084       at io.joern.console.InteractiveShell.startInteractiveShell$(BridgeBase.scala:230)
#49 5.084       at io.joern.joerncli.console.ReplBridge$.startInteractiveShell(ReplBridge.scala:6)
#49 5.084       at io.joern.console.BridgeBase.run(BridgeBase.scala:210)
#49 5.084       at io.joern.console.BridgeBase.run$(BridgeBase.scala:43)
#49 5.084       at io.joern.joerncli.console.ReplBridge$.run(ReplBridge.scala:6)
#49 5.084       at io.joern.joerncli.console.ReplBridge$.main(ReplBridge.scala:11)
#49 5.084       at io.joern.joerncli.console.ReplBridge.main(ReplBridge.scala)

```
**To Reproduce**

1. Steps to reproduce the behavior:
2. Execute the docker build command. Within the build process, install JDK 19 and run the ./joern-install.sh script.
3. Initiate the Docker container. Inside the container, execute either joern some_script.scala or joern -v.
4. Alternatively, run a Python script that internally calls joern -v or joern some_script.scala.
5. Observe the resulting error.

**Expected Behavior**: 
The Joern application should execute successfully without errors.

**Desktop (please complete the following information):**
 - Ubuntu 18.04/CentOS 7 (the same behaviour)
 - Joern Version, latest form 03/06/2024
 - jdk-19.0.2

How can I fix such error?

**Comment by maltek** [comment] 2024-03-06 14:33
probably running docker with a tty (`docker run -it ...`) will fix your immediate error

@mpollmeier the problem reproduces with any redirected input, e.g. just `./srp < /dev/null` - do you think we can add a fallback for this?

**Comment by lyriccoder** [comment] 2024-03-06 15:02
Running with `-it` doesn't help, I have still the same issue

**Comment by lyriccoder** [comment] 2024-03-06 15:34
I found smth on the different forums:
seems the error is related to `jansi` library or `JLine`. Do u have the recent versions of those libraries?

**Comment by mpollmeier** [comment] 2024-03-06 15:43
we currently depend on jline 3.19.0 - I don't think we (or the scala repl) is too deeply interweaved with that specific version, but haven't tried to upgrade

```
sbt console/dependencyTree

...
[info]   | | | +-org.scala-lang:scala3-compiler_3:3.3.1
[info]   | | | | +-org.jline:jline-reader:3.19.0
[info]   | | | | | +-org.jline:jline-terminal:3.19.0
[info]   | | | | |
[info]   | | | | +-org.jline:jline-terminal-jna:3.19.0
[info]   | | | | | +-net.java.dev.jna:jna:5.3.1
[info]   | | | | | +-org.jline:jline-terminal:3.19.0
[info]   | | | | |
[info]   | | | | +-org.jline:jline-terminal:3.19.0
...
```

**Comment by mpollmeier** [comment] 2024-03-06 15:44
I'll take a deeper look tomorrow

**Comment by lyriccoder** [comment] 2024-03-07 06:52
> I found smth on the different forums: seems the error is related to `jansi` library or `JLine`. Do u have the recent versions of those libraries?

I found similar bug here: https://github.com/scala/bug/issues/12167.

**Comment by mpollmeier** [comment] 2024-03-07 11:30
According to https://github.com/scala/bug/issues/12167#issuecomment-762928406 we can fix this by adding jansi to the classpath. That would be an easy solution, but I'd like to be able to reproduce this first. Here's what I tried:

```
# on host machine
cd joern
sbt stage

# now start the docker image and run joern
docker run -ti -v .:/shared ubuntu:22.04
apt update
apt install openjdk-21-jdk
cd /shared
./joern
```

![grafik](https://github.com/joernio/joern/assets/506752/803fd07c-c853-45a8-9059-2fb924383370)

**Comment by mpollmeier** [comment] 2024-03-07 12:36
> @mpollmeier the problem reproduces with any redirected input, e.g. just ./srp < /dev/null - do you think we can add a fallback for this?

I'd like to avoid any custom handling on our side, but playing with the classpath might be an option. I fiddled around a little bit without real success, but here's what I've got, for future reference: https://github.com/mpollmeier/scala-repl-pp/commit/29368ffe4cc09a79b0450d1ddcc88a739239447a

**Comment by mpollmeier** [comment] 2024-03-08 07:51
It might be worth to auto-fallback to a dumb terminal if the regular terminal doesn't work, see https://github.com/mpollmeier/scala-repl-pp/pull/147

**Comment by mpollmeier** [comment] 2024-03-11 17:17
yes as of https://github.com/joernio/joern/pull/4305 we upgraded the repl, would be good if you give it a try

**Comment by mpollmeier** [comment] 2024-03-12 09:32
Thanks for checking. That's a different issue, looks like the CPG you're trying to load is corrupt, or at least doesn't conform to the schema. Will close this now, feel free to open a follow-up.

**Closed by mpollmeier** 2024-03-12 09:32 UTC
Labels: bug
