### ISSUE TITLE
[Bug][rubysrc2cpg] do keyword issue

### ISSUE THREAD

**Issue by ankit-privado** [joernio/joern#3175] opened 2023-07-20 18:23 UTC
Describe the bug
getting parser error - ` mismatched input 'do' expecting <EOF> at line 1`
To Reproduce
```
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.clean_with :truncation, except: %w(ar_internal_metadata)
  end
end
```

**Comment by ankit-privado** [comment] 2023-07-20 20:17
@xavierpinho i'm not confident about whether this issue is related to `do` keyword or not, but this fragment of code throwing error.

**Comment by xavierpinho** [comment] 2023-07-21 10:43
> @xavierpinho i'm not confident about whether this issue is related to `do` keyword or not, but this fragment of code throwing error.

Indeed, the issue is still #3040, so I'll be closing this one. But thanks for the sample either way!

**Closed by xavierpinho** 2023-07-21 10:43 UTC
Labels: bug
