### ISSUE TITLE
[Bug] Ruby Parsing issue

### ISSUE THREAD

**Issue by ankit-privado** [joernio/joern#3045] opened 2023-07-06 00:32 UTC
Describe the bug

Ruby parser fails for the below code
Please keep the conversation English! Make it easy for us and share your input code or a minified example.

To Reproduce
Load [this](https://github.com/aidear323/Transactions_app/blob/5f3319105893d0029edcf18ec2aa02d5f7297fa1/app/models/transaction.rb#L8) code in the Ruby parser and see it failing.

Expected behavior
Parsing should pass

Screenshots
NA

Desktop (please complete the following information):
NA

Additional context
NA

**Comment by xavierpinho** [comment] 2023-07-06 17:33
Closing this as a duplicate of #3043

**Closed by xavierpinho** 2023-07-06 17:33 UTC
Labels: bug
